name: Build and deploy ASP.Net Core app to Azure Web App - TuneVault

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      # Publish ra thư mục cục bộ tên là 'publish'
      - name: dotnet publish
        run: dotnet publish -c Release -o ./publish

      # Login vào hệ thống Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9DEFEB90FAC84F9BAA1A455227F3ABE6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_790119198D15473BBE8AD914B782A9B4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BC48E0D0C53B47D49E7E0A7D2BFE86B8 }}

      # Chỉ định chính xác package là thư mục ./publish ở trên
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TuneVault'
          slot-name: 'Production'
          package: ./publish
